# Generated by Django 5.2.8 on 2026-05-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('tipo_persona', models.CharField(choices=[('interno', 'Interno'), ('gendarme', 'Gendarme'), ('externo', 'Externo')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
