# Generated by Django 5.2.8 on 2026-05-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_persona_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='foto',
        ),
    ]
