# Generated by Django 5.2.8 on 2026-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto_rostro',
            field=models.ImageField(blank=True, null=True, upload_to='rostros/'),
        ),
    ]
