# Generated by Django 5.2.8 on 2026-05-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto_rostro',
            field=models.ImageField(blank=True, null=True, upload_to='rostros_recortados/'),
        ),
    ]
