# Generated by Django 5.2.8 on 2026-05-11 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_persona_foto_rostro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('camara', models.CharField(max_length=100)),
                ('coincidencia', models.FloatField()),
                ('resultado', models.CharField(choices=[('PERMITIDO', 'Permitido'), ('DENEGADO', 'Denegado'), ('REVISION', 'Revisión')], max_length=20)),
                ('foto_validacion', models.ImageField(blank=True, null=True, upload_to='validaciones/')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.persona')),
            ],
        ),
    ]
