# Generated by Django 5.2.8 on 2026-05-12 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_acceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='RostroCapturado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='rostros_dataset/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rostros', to='usuarios.persona')),
            ],
        ),
    ]
