# Generated by Django 5.2.8 on 2026-05-13 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rostrocapturado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuellaDactilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='huella', to='usuarios.persona')),
            ],
        ),
    ]
