# Generated by Django 5.2.8 on 2026-05-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_huelladactilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='nombre_detectado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
