# Generated by Django 5.2.8 on 2026-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_acceso_nombre_detectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
