# Generated by Django 5.2.8 on 2026-05-27 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_enrolamiento',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completo', 'Completo')], default='pendiente', max_length=20),
        ),
    ]
